# Site settings
title: João Victor Pessoa
email: jvpessoa10@hotmail.com
url: https://jvpessoa10.github.io
description: ""
keywords: "asd,asd,asd"
skills: "Front-end Developer - Desenvolvedor de sistemas - Mobile"
meta_author: Pessoa João

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 072e4c
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: João Victor Pessoa
  location: Localização
  social: Redes Sociais
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Joao_Victor_P10
  - title: facebook
    url: https://www.facebook.com/jvpessoa10
  - title: stack-overflow
    url: https://stackoverflow.com/users/6292811/jvpessoa10
  - title: bitbucket
    url: http://bitbucket.org/jvpessoa
  - title: github
    url: http://github.com/jvpessoa10

# Postal address (add as many lines as necessary)
address:
  - line: Rua doutor Geraldo de Andrade, 101
  - line: Espinheiro, Recife

# Credits content
credits: ""

# Build settings
markdown: kramdown
permalink: pretty
